name: cd-storybook
on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  trigger_design_system_workflow:
    permissions:
      contents: none
    if: github.repository == 'opf/openproject'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream workflow
        env:
          TOKEN: ${{ secrets.OPENPROJECT_CI_TOKEN }}
          DS_CD_WORKFLOW_ID: build-docs.yml
          DS_REPOSITORY: opf/design-system
        run: |
          curl -i --fail -H"authorization: Bearer $TOKEN" \
            -XPOST -H"Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$DS_REPOSITORY/actions/workflows/$DS_CD_WORKFLOW_ID/dispatches \
          -d '{ "ref": "dev", "inputs": { "ref": "${{ github.ref }}" }}'
